name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours at minute 0
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create dist directory
        run: |
          rm -rf dist || true
          mkdir -p dist

      - name: Generate pacman-contribution-graph (action)
        # This action generates SVG(s) in the runner workspace root (expected)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
        # If the action requires additional inputs change above accordingly

      - name: Collect generated SVG files into dist
        run: |
          # Adjust these names if the generator writes different filenames.
          # We attempt to move common output names into dist/
          if [ -f "pacman-contribution-graph.svg" ]; then mv pacman-contribution-graph.svg dist/; fi
          if [ -f "pacman-contribution-graph-dark.svg" ]; then mv pacman-contribution-graph-dark.svg dist/; fi
          # Some versions write into ./output or ./dist already. Move likely candidates:
          if [ -d "output" ]; then mv output/* dist/ || true; fi
          if [ -d "dist" ]; then echo "dist exists"; fi
          ls -la dist || true

      - name: Commit debug info (optional)
        if: always()
        run: |
          echo "Generated files in dist:"
          ls -la dist

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
